### PR TITLE
#188 Add confirmation alert for 'clear tasks' action

### PR DESCRIPTION
**Pull request by ccalamos**
Related to issue #188, quick easy solution to add confirmation for clearing tasks.

### CODE REVIEW

**Comment by angrykoala** [comment]
@ccalamos One question, it was not defined in the issue, but it would be cool if the config menu close  after confirming the "clear tasks" action (and not when cancelling)

Do you think it is easy for you to do it as part of this PR or it would be better to open a separate issue for this?

**Comment by ccalamos** [comment]
I will look into it 👍

**Comment by angrykoala** [comment]
Everything looks fine, but closing the menu when clicking clear task is weird, please, remove the `modal-action modal-close` from the button class to avoid this behaviour

**Comment by ccalamos** [comment]
So to confirm you want the confirmation modal to appear on top of the config menu and then if you say yes to bring you to main screen and if you say no then show config modal?

**Comment by angrykoala** [comment]
Yes, that's the ideal behavior if you can do it with relative ease
Thanks!

**Comment by ccalamos** [comment]
I will work on having it not close out but I say we finish this PR and open a new issue and I will continue to work on it.

**Pull request merged**
