### PR TITLE
Avoid rendering Config menu when not needed

### PR DESCRIPTION
**Pull request by panvourtsis**
this PR is fixing the #141

### CODE REVIEW

**Comment by angrykoala** [comment]
Thanks for contributing.
This solution seems right, but I'm not sure why are you storing the flag `configMenu` in the actual app configuration (which will be stored). This could be simply stored in AppStatus (no data from here is actually stored anywhere), defaulting to false, the remaining logic should be the same

**Comment by panvourtsis** [comment]
i though you needed for some reason based on your code and description. I can simply store it, shall i?

**Comment by angrykoala** [comment]
Yes, I'm sorry this stuff is not very well documented (just yesterday I refactored the config)

In a nutshell, AppStatus is simply a way of stored global variables (like flags to render config menu), while app_config is going to actually be stored across sessions.

A variable on AppStatus (or any other place) should be enough

**Comment by angrykoala** [comment]
* I don't think we need this variable as part of the config in config menu. It should be enough with having it in appstatus
* Please, make the pr to dev :)

**Comment by panvourtsis** [comment]
you are right, getting familiar with you code now

**Comment by angrykoala** [comment]
Don't worry that's what code reviews are for

**Comment by angrykoala** [comment]
After testing your version, I found a problem with doing this. When closing the config menu, it closes suddenly (because it stops being rendered). I think my idea of stop rendering config is not as simple as I though. Do you have any idea on how to improve this?

**Comment by panvourtsis** [comment]
I've seen the same while i was doing it. Vue offers this modal but even if you load it with template inside the page the script will be there. Even on online demos i can see that. What i've seen working is [here](https://www.npmjs.com/package/vue-js-modal) demos are [here](http://vue-js-modal.yev.io/)

Let me know if these are working in your case though

**Comment by angrykoala** [comment]
To be honest, I don't think is worth it adding another library for this, the performance impact of config is not that big. I'm afraid I'll have to close this PR, but thanks for the investigation, I'll close the issue as it is not worth it for something as simple as the config

**Pull request closed without merging**
