### PR TITLE
introduce pre commit

### PR DESCRIPTION
**Pull request by panvourtsis**
what we discussed on #145

### CODE REVIEW

**Comment by angrykoala** [comment]
pre-commit should be "test" instead of jshint, so it runs both, the tests and jshint

**Comment by panvourtsis** [comment]
do you have to run clean everytime for testing?

**Comment by angrykoala** [comment]
Not really, Maybe it would be better removing the clean and jshint from npm test and add those to your precommit. What do you think?

**Comment by panvourtsis** [comment]
on my projects i have two scripts runnning on precommit the tests and the linting. In your case 

`["_mocha", "jshint"]`

**Comment by angrykoala** [comment]
the tests also use istanbul, wouldn't it be better to execute the npm scripts I already have?
```
scripts:{
  "test": "istanbul cover _mocha",
  "clean": ...,
  "jshint": ...
},
precommit:[ "test","clean","jshint"]
```

Does this make sense?

**Comment by panvourtsis** [comment]
this is what i use (without the clean)

**Comment by angrykoala** [comment]
Yeah, I'll give it a shot and see if it makes easier contributions. Please, point the PR to the dev branch

**Pull request merged**
