### PR TITLE
Improved logo (minor changes)

### PR DESCRIPTION
**Pull request by juanluischaurant**
## Description of the PR
Improved Logo Design

### CODE REVIEW

**Comment by angrykoala** [comment]
Please, merge against the `dev` branch

**Comment by angrykoala** [comment]
Hi @juanluischaurant I just saw that the images you uploaded are not squares.
Could you please adapt the images (and maybe change the logo accordingly as well) to be squared please?

**Comment by juanluischaurant** [comment]
Oh, sorry, my bad. 
I will fix it.

**Comment by juanluischaurant** [comment]
I corrected the logos, but now I cannot find a way to update the changes, could I get some help?

**Comment by angrykoala** [comment]
Ok, I think you removed your fork, or updated it in a weird way, I don't know.

You may close this PR and open a new one

**Comment by juanluischaurant** [comment]
Okay, thanks!

**Pull request closed without merging**
